server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET:dev-secret-mora-biti-dovoljno-dug-za-hs256-min-256-bitova-ovaj-string-je-dug}
  expiration-ms: 86400000

internal:
  service:
    token: ${INTERNAL_SERVICE_TOKEN:}
